[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "asr-quests-tools"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [ "jsonschema" ]

[project.scripts]
validate-quests = "utilities.validate_quests:main"

[tool.setuptools.packages.find]
where = [ "." ]
include = [ "utilities*" ]
